version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - kbdata:/var/lib/postgresql/data

volumes:
  kbdata:
    external: true
